products/urls.py
from django.conf.urls.static import static
from django.urls import path

from productparser.settings import MEDIA_ROOT, MEDIA_URL
from .views import *
from .weekly_new_product_report import get_new_product_details
from .newDesignViews import *


app_name = 'products'
urlpatterns = [
                  path('home', home, name='home'),

                  path('scrapping_job_links', scrapping_job_links, name='scrapping_job_links'),
                  path('delete_scrapping_links', delete_scrapping_links, name='delete_scrapping_links'),

                  path('products', products, name='products'),

                  path('products_new', products_new, name='products_new'),
                  path('competitors_info_new', competitors_info_new, name='competitors_info_new'),

                  path('products/upload_products', upload_products, name='upload_products'),
                  path('delete_products_info', delete_products_info, name='delete_products_info'),
                  path('update_products_smart_price_info', update_products_smart_price_info,
                       name='update_products_smart_price_info'),
                  path('products/upload_product_competitors', upload_product_competitors,
                       name='upload_product_competitors'),

                  # Product Details
                  path('products/detail/<int:product_id>/', product_detail, name='product_detail'),
                  path('add_product_competitor', add_product_competitor, name='add_product_competitor'),
                  path('delete_product_competitor', delete_product_competitor, name='delete_product_competitor'),
                  path('fetch_product_details', fetch_product_details, name='fetch_product_details'),
                  path('fetch_testing_info', fetch_testing_info, name='fetch_testing_info'),

                  path('categories', categories, name='categories'),
                  path('brands', brands, name='brands'),
                  path('suppliers', suppliers, name='suppliers'),
                  path('rules/add', add_rules, name='add_rules'),
                  path('add_rules_csv', add_rules_csv, name='add_rules_csv'),
                  path('edit_rule', edit_rule, name='edit_rule'),
                  path('get_rule_detail', get_rule_detail, name='get_rule_detail'),
                  path('rules', rules, name='rules'),
                  path('delete_rule', delete_rule, name='delete_rule'),
                  path('delete_all_rule', delete_all_rule, name='delete_all_rule'),
                  path('filter_costs_viewer', filter_costs_viewer, name='filter_costs_viewer'),
                  path('products_sku', products_sku, name='products_sku'),

                  path('new_product_details', get_new_product_details, name='get_new_product_details'),

                  path('daily_update', daily_update, name='daily_update'),
                  path('instant_push', instant_push, name='instant_push'),
                  path('register_push_event', register_push_event, name='register_push_event'),
                  path('register_products_job', register_products_job, name='register_products_job'),
                  path('register_product_competitor_job', register_product_competitor_job,
                       name='register_product_competitor_job'),
                  path('update_all_daily_report', update_all_daily_report, name='update_all_daily_report'),
                  path('update_smart_price', update_smart_price, name='update_smart_price'),
                  path('update_smart_price_of_product', update_smart_price_of_product, name='update_smart_price_of_product'),

                  path('competitors_info', competitors_info, name='competitors_info'),
                  path('competitors_info/all_competitors_info', all_competitors_info, name='all_competitors_info'),
                  path('updated_on_thenx', updated_on_thenx, name='updated_on_thenx'),
                  path('delete_competitor_info', delete_competitor_info, name='delete_competitor_info'),
                  path('update_competitor_info', update_competitor_info, name='update_competitor_info'),
                  path('update_all_competitor_info', update_all_competitor_info, name='update_all_competitor_info'),
                  path('send_email', send_email, name='send_email'),
                  path('download_csv_file', download_csv_file, name='download_csv_file'),
                  path('export_csv_file', export_csv_file, name='export_csv_file'),
                  path('export_products_csv_file', export_products_csv_file, name='export_products_csv_file'),
                  path('export_scraping_csv_file', export_scraping_csv_file, name='export_scraping_csv_file'),

                  # dump information
                  path('dump_categories_job', dump_categories_job, name='dump_categories_job'),
                  path('dump_brands_job', dump_brands_job, name='dump_brands_job'),
                  path('dump_suppliers_job', dump_suppliers_job, name='dump_suppliers_job'),
                  path('dump_competitors_info_job', dump_competitors_info_job, name='dump_competitors_info_job'),
                  path('dump_products_info', dump_products_info, name='dump_products_info'),

                  # cron logs
                  path('job_logs', job_logs, name='job_logs'),
                  path('job_detail', job_detail, name='job_detail'),
                  path('delete_all_data', delete_all_data, name='delete_all_data'),
                  path('delete_competitors_data', delete_competitors_data, name='delete_competitors_data'),

                  path('users_info', users_info, name='users_info'),
                  path('reset_password', reset_password, name='reset_password'),
                  path('delete_user', delete_user, name='delete_user'),
                  path('update_permission_of_user', update_permission_of_user, name='update_permission_of_user'),
                  path('add_new_user', add_new_user, name='add_new_user'),

                  # product fetching jobs
                  path('test_product_scrapping', test_product_scrapping, name='test_product_scrapping'),
                  path('test_product_cron', test_product_cron, name='test_product_cron'),
                  path('test_product_fetching_items', test_product_fetching_items, name='test_product_fetching_items'),
                  path('test_email_csv_files', test_email_csv_files, name='test_email_csv_files'),
                  path('test_product_competitor_link', test_product_competitor_link, name='test_product_competitor_link'),

              ] + static(MEDIA_URL, document_root=MEDIA_ROOT)

products/views.py
import io
import os
from datetime import timedelta
from .export_rules import *
from django.conf import settings
from django.contrib.auth import authenticate
from django.contrib.auth import login as login_auth
from django.contrib.auth import logout as logout_auth
from django.contrib.auth.decorators import login_required
from django.db.models import Count
from django.db.models import Q
from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render, redirect

from .add_rule import Rule
from .add_rule_csv_file import AddCSVRule
from .edit_existing_rule import EditRule
from .fetch_product_detail import FetchProductDetail
from .rules_filter import RulesFilter
from .utils import *


def login(request):
    context = {}
    if request.method == 'POST':
        email = request.POST['email'] if 'email' in request.POST else ''
        password = request.POST['password'] if 'password' in request.POST else ''
        email = email.lower().strip()
        user = authenticate(username=email, password=password)
        if user:
            if user.is_active:
                login_auth(request, user)
                return redirect('products:home')
        context = {'error': 'Email or Password is wrong'}
    return render(request, 'products/login.html', context=context)


def logout(request):
    logout_auth(request)
    return redirect('login')


def home(request):
    competitor_count = ProductCompetitorSites.objects.count()
    competitor_link = ProductCompetitorsLinks.objects.count()
    total_brands = Brands.objects.count()
    total_suppliers = Suppliers.objects.count()
    total_categories = Categories.objects.count()
    total_products = Products.objects.count()

    rules_info = Rules.objects.aggregate(
        margin_rules=Count('pk', filter=Q(rule_type=3)),
        warranty_rules=Count('pk', filter=Q(rule_type=1)),
        local_cost_rules=Count('pk', filter=Q(rule_type=4)),
        thenx_cost_rules=Count('pk', filter=Q(rule_type=5)),
        competitor_rules=Count('pk', filter=Q(rule_type=6)),
        total_rules=Count('pk')
    )

    total_rules = rules_info['total_rules']
    margin_rules = rules_info['margin_rules']
    warranty_rules = rules_info['warranty_rules']
    local_cost_rules = rules_info['local_cost_rules']
    thenx_cost_rules = rules_info['thenx_cost_rules']
    competitor_rules = rules_info['competitor_rules']

    rank_information = AdminLogOfJobToShow.objects.filter(created_at__date=datetime.datetime.now().date()).aggregate(
        same_prices=Count('pk', filter=Q(price_change_effect=1)),
        exceeded_prices=Count('pk', filter=Q(price_change_effect=2)),
        decreased_prices=Count('pk', filter=Q(price_change_effect=3)),
        total_prices=Count('pk', filter=Q(price_change_effect__in=[1, 2, 3])),
        updated_prices=Count('pk', filter=Q(is_approved=True)),
        is_competitor_rule_applied=Count('pk', filter=Q(is_competitor_rule_applied=True)),
        is_margin_rule_applied=Count('pk', filter=Q(is_margin_rule_applied=True)),
        is_original_price_applied=Count('pk', filter=Q(is_original_price_applied=True))
    )

    total_prices = rank_information['total_prices']
    same_prices = rank_information['same_prices']
    exceeded_prices = rank_information['exceeded_prices']
    decreased_prices = rank_information['decreased_prices']
    updated_prices = rank_information['updated_prices']
    is_competitor_rule_applied = rank_information['is_competitor_rule_applied']
    is_margin_rule_applied = rank_information['is_margin_rule_applied']
    is_original_price_applied = rank_information['is_original_price_applied']

    crons_info = ProductCompetitorSitesReference.objects.filter(
        created_at__date=datetime.datetime.now().date()).aggregate(
        total_crons=Count('pk'),
        succeded_crons=Count('pk', filter=Q(is_error=False)),
        failure_crons=Count('pk', filter=Q(is_error=True))
    )

    total_crons = crons_info['total_crons']
    succeded_crons = crons_info['succeded_crons']
    failure_crons = crons_info['failure_crons']

    weekly_new_products = WeeklyReportNewProducts.objects.all().last()

    context = {'competitor_count': competitor_count, 'competitor_link': competitor_link, 'total_brands': total_brands,
               'total_suppliers': total_suppliers, 'total_categories': total_categories,
               'total_products': total_products, 'total_rules': total_rules, 'margin_rules': margin_rules,
               'warranty_rules': warranty_rules, 'local_cost_rules': local_cost_rules,
               'thenx_cost_rules': thenx_cost_rules,
               'competitor_rules': competitor_rules, 'total_crons': total_crons, 'failure_crons': failure_crons,
               'succeded_crons': succeded_crons, 'total_prices': total_prices, 'exceeded_prices': exceeded_prices,
               'same_prices': same_prices, 'decreased_prices': decreased_prices, 'updated_prices': updated_prices,
               'is_competitor_rule_applied': is_competitor_rule_applied,
               'is_margin_rule_applied': is_margin_rule_applied,
               'is_original_price_applied': is_original_price_applied,
               'weekly_new_products': weekly_new_products
               }
    return render(request, 'products/dashboard.html', context=context)


@login_required
def products(request):
    if request.method == 'POST':
        data = request.POST
        draw = int(data['draw']) if 'draw' in data else 0
        start_index = int(data['start']) if 'start' in data else 0
        length = int(data['length']) if 'length' in data else 0

        supplier_ = request.POST['supplier']
        category_ = request.POST['category']
        product_ = request.POST['product']

        search_parameter = data['search[value]'] if 'search[value]' in data else ''

        if supplier_ and supplier_ != 'select':
            supplier_ = int(supplier_)
        else:
            supplier_ = ''
        if category_ and category_ != 'select':
            category_ = int(category_)
        else:
            category_ = ''

        _products = Products.objects.all().order_by('id')
        # if search_parameter: _products = Products.objects.filter(Q(name__icontains=search_parameter) | Q(
        # sku__icontains=search_parameter) | Q(brand__name__icontains=search_parameter) | Q(
        # supplier__name__icontains=search_parameter) | Q(categories__name__icontains=search_parameter) ).order_by(
        # 'id') _products = _products.distinct()

        if supplier_:
            _products = _products.filter(supplier__id=supplier_)
        if category_:
            _products = _products.filter(categories__id=category_)
        if product_:
            _products = _products.filter(Q(name__icontains=product_) | Q(sku__icontains=product_))

        if supplier_ is not None or category_ is not None or product_ is not None:
            _products = _products.distinct()

        def extract(obj, key):
            categories_ = [x.name for x in obj.categories.all()]
            categories_ = ','.join(categories_)

            supplier_ = 'N/A'
            if obj.supplier:
                supplier_ = obj.supplier.name

            # pci = ProductCalculationInformation.objects.filter(product=obj).last()
            # if pci:
            #     local_cost_supplier = pci.local_cost_supplier
            #     thenx_cost_supplier = pci.thenx_cost_supplier
            #     vat = pci.vat
            #     all_cost_price = pci.all_cost_price
            #     whole_sale_price = pci.whole_sale_price
            #     gross_profit_whole_sale = pci.gross_profit_whole_sale
            #     retail_sale_price = pci.retail_sale_price
            #     gross_profit_retail_sale = pci.gross_profit_retail_sale
            #     whole_sale_margin = pci.whole_sale_margin
            #     retail_margin = pci.retail_margin
            #     old_price_all_cost = 'N/A'
            #     last_update = str(pci.created_at)
            # else:
            response_ = calculate_price_detail_of_product(obj)
            smart_price_set = 'N/A'
            if obj.is_smart_price_already_set:
                smart_price_set = obj.smart_price_value

            local_cost_supplier = response_['local_cost']
            local_cost_supplier_check = response_['local_cost_is']
            if local_cost_supplier_check != 'N/A':
                local_cost_supplier = round(local_cost_supplier, 2)
            else:
                local_cost_supplier = 'N/A'

            thenx_cost_supplier = response_['thenx_cost']
            thenx_cost_supplier_check = response_['thenx_cost_is']
            if thenx_cost_supplier_check != 'N/A':
                thenx_cost_supplier = round(thenx_cost_supplier, 2)
            else:
                thenx_cost_supplier = 'N/A'

            vat = response_['vat']
            if vat and vat != 'N/A':
                vat = round(vat, 2)

            all_cost_price = response_['all_cost_price']
            if all_cost_price and all_cost_price != 'N/A':
                all_cost_price = round(all_cost_price, 2)

            whole_sale_price = response_['whole_sale_rounded']
            gross_profit_whole_sale = response_['gross_profit_whole_sale']
            gross_profit_whole_sale_margin = response_['margin_whole_sale']
            whole_sale_margin = response_['whole_sale_margin']
            whole_sale_rule_unit = response_['whole_sale_rule_unit']

            retail_sale_price = response_['retail_price_rounded']
            gross_profit_retail_sale = response_['gross_profit_retail_price']
            gross_profit_retail_sale_margin = response_['margin_retail_price']
            retail_margin = response_['retail_price_margin']
            retail_price_rule_unit = response_['retail_price_rule_unit']

            old_price_all_cost = 'N/A'
            last_update = 'N/A'

            is_smart_price_set_applied = 'No'
            if obj.is_smart_price_already_set:

products/templates/products/product_detail/competitors_list.html
<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <div class="row">
                <div class="col-lg-6"><h3 class="box-title m-b-0">Product Competitors List</h3></div>
                <div class="col-lg-6 text-right">
                    <button class="btn btn-info" onClick="competitors_view()">View Detail</button>
                </div>
            </div>
            <hr>
            <div class="competitors_view" style="display:none">
                <div class="row" style="font-weight: 700; ">
                    <div class="col-md-4">
                        Competitor Site
                    </div>
                    <div class="col-md-4">
                        Competitor Link
                    </div>
                    <div class="col-md-2">
                        Action
                    </div>
                    <div class="col-md-2">
                        <button class="btn btn-primary" id="exampleModalBtn" data-target="#exampleModal" data-toggle="modal" type="button">
                            Add New
                        </button>
                    </div>

                    <div aria-labelledby="exampleModalLabel1" class="modal fade" id="exampleModal" role="dialog"
                         tabindex="-1">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <button aria-label="Close" class="close" data-dismiss="modal" type="button"><span
                                            aria-hidden="true">&times;</span></button>
                                    <h4 class="modal-title" id="exampleModalLabel1">New message</h4></div>
                                <div class="modal-body">
                                    <form>
                                        <div class="form-group">
                                            <label class="control-label" for="message-text">Select Competitor
                                                Site:</label>
                                            <select class="form-control" id="competitor_site">
                                                {% for obj in product_competitors %}
                                                <option value="{{obj.id}}">{{obj.name.title}}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                        <div class="form-group">
                                            <label class="control-label" for="message-text">Type Competitor
                                                Link:</label>
                                            <input class="form-control" id="competitor_link">
                                        </div>
                                        <div class="error_div" style="color: red"></div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button class="btn btn-default" data-dismiss="modal" type="button">Close</button>
                                    <button class="btn btn-primary" onClick="form_submit()" type="button">Save
                                        Information
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
                <hr>
                <div class="competitors_main_div">
                    {% for obj in competitors %}
                    <div class="row competitorsclasss" id="competitor{{obj.id}}">
                        <div class="col-md-4">{{obj.site_reference.name}}</div>
                        <div class="col-md-4">{{obj.link}}</div>
                        <div class="col-md-4">
                            <button class="btn btn-danger" onClick="delete_competitor({{obj.id}})">Delete</button>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</div>

products/templates/products/product_detail/fetch_product_details.html
<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <div class="row">
                <div class="col-lg-6"><h3 class="box-title m-b-0">Fetch Product Details</h3></div>
                <div class="col-lg-6 text-right">
                    <button class="btn btn-info" onClick="fetch_product_details()">Fetch Details</button>
                </div>
            </div>
            <hr>
            <div class="product_details_view_fetch">
                <div class="row" style="font-weight: 700;">
                    <div class="col-md-4">Site URL</div>
                    <div class="col-md-4">Original Price</div>
                    <div class="col-md-4">Promotion Price</div>
                </div>
                <hr>
            </div>
        </div>
    </div>
</div>

products/templates/products/product_detail/product_detail.html
{% extends 'products/base.html' %} {% load static %} {% block style_cdn_links %}
<link href="{% static 'plugins/bower_components/datatables/jquery.dataTables.min.css' %}" rel="stylesheet"
      type="text/css"/>
<link href="https://cdn.datatables.net/buttons/1.2.2/css/buttons.dataTables.min.css" rel="stylesheet"
      type="text/css"/> {% endblock %} {% block stylesheet %} {% endblock %} {% block bodyblock %}

<style>
    .col_bottom {
        margin-bottom: 0;
    }
    
    .price-box {
        /* background: #fbfbfb; */
        display: flex;
        align-items: center;
        margin-bottom: 1em;
        padding: .4em 1em;
    }
    
    .price-box .space {
        flex: auto;
    }
    
    .price-box .p-badge {
        background: #dec10b;
        color: #fff;
        font-size: 10px;
        padding: 0 1em;
        border-radius: 1em;
        margin-left: 1em;
    }
    
    .price-box .price-digit {
        color: #ffffff;
        font-weight: 700;
    }
    
    .price-digit i {
        color: #000 !important;
    }
    
    .price-box .digit {
        font-weight: 800;
        font-size: 20px;
    }
    
    .price-box .cal-box {
        padding: 1em 1em !important;
        /* width: 100%; */
        /* margin: .5em 0; */
        /*background: #d7ca77;*/
        background: #aba583;
        border-radius: 1em;
        color: #ffffff;
        width: 20%;
    }
    
    .cal-box:last-child {
        background: #f6d206;
        width: 27%;
    }
    
    .price-box h5:first-child {
        color: #444;
        /* border-bottom: 2px solid #dec10b; */
    }
    
    .price-box h5:nth-child(3) {
        font-size: 13px;
        color: #dec10b;
        font-weight: 700;
    }
    
    .price-box h5:nth-child(3) i {
        color: #444;
    }
    
    .price-box .sub span {
        color: #dec10b;
        font-weight: 700;
    }
    
    .price-box .sub i {
        margin-left: .2em;
        color: #444 !important;
    }
    
    @media screen and (max-width:800px) {
        .price-box {
            /* flex-shrink: unset; */
            flex-flow: column;
            text-align: center;
        }
        .cal-box {
            padding: 1em 2em !important;
            width: 100%;
            margin: .5em 0;
            background: #f3f3f3;
        }
    }

    .competitorsclasss {
        margin-bottom: 10px;
    }

    .product_details_view_fetch_row {
        margin-top: 20px;
    }


    .competitorsListNew td {
        padding: 3px 5px!important;
        font-size: 13px!important;
    }
    .competitorsListNew th {
        padding: 3px 5px!important;
        font-size: 13px!important;
    }

    .competitorsList td {
        padding: 3px 5px!important;
        font-size: 13px!important;
    }
    .competitorsList th {
        padding: 3px 5px!important;
        font-size: 13px!important;
    }
    .competitorsList .sorting_1{
        background-color: #ffffff!important;
    }
    .competitorsList .odd{
        background-color: #ffffff!important;
    }
    .competitorsList tbody tr:hover {
        background-color: #ffffff!important;
    }
    .competitorsList .divider {
        background-color: #EDF1F5!important;
    }
    .competitorsList .colorRed {
        color: #ff0000!important;
    }
    .competitorsList .colorRedNoStock {
        color: #f0000b !important;
    }
    .competitorsList .colorDark {
        color: #cccccc!important;
    }
    .competitorsList .colorGreen {
        color: #298029!important;
    }
    .competitorsList .colorGreenBackground {
        background: #298029!important;
        color: white!important;
        font-weight:600!important;
    }
    .competitorsList .colorRedBackground {
        background: #ff0000!important;
        color: white!important;
        font-weight:600!important;
    }


    #dataTable tr td:nth-child(3){
        word-wrap: break-word;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        min-width: 50px !important;
        max-width: 150px !important;
    }

</style>
<div class="row">
    <div class="col-sm-12">
        <div class="white-box">
            <h3 class="box-title m-b-0">Product Detail</h3>
            <hr>
            <div class="row">
                <div class="col-lg-6"><h3 class="box-title m-b-0">{{product.name}}</h3></div>
                <div class="col-lg-6 text-right"><h3 class="box-title m-b-0">
                    {% if product.supplier %}
                    <b>Supplier: </b>{{product.supplier.name}}
                    {% endif %}
                </h3></div>
            </div>
        </div>
    </div>
</div>

{% include 'products/product_detail/price_calculation_view.html' %}
{% include 'products/product_detail/competitors_list.html' %}
{% include 'products/product_detail/fetch_product_details.html' %}


{% endblock %}
{% block javascript %}
<script src="{% static 'plugins/bower_components/datatables/jquery.dataTables.min.js' %}"></script>

<script>

    function form_submit(){
        site_reference = $('#competitor_site').val()
        competitor_link = $('#competitor_link').val()
        if (competitor_link == ''){
            $('.error_div').html('Note: Competitor Link is compulsary');
        }
        else {
            $.post("{% url 'products:add_product_competitor' %}",
              {csrfmiddlewaretoken: '{{ csrf_token }}', competitor_id: site_reference, competitor_link: competitor_link, product_id: {{product.id}}},
              function(data){
                $('.error_div').empty();
                $('.error_div').html('Added Successfully');
                $('#competitor_link').val('');
                $('#exampleModal').modal('toggle');

                $('.competitorsclasss').remove();

                for (var i=0; i<data.length; i++){
                    $('.competitors_main_div').append('\
                        <div class="row competitorsclasss" id="competitor'+data[i].id+'">\
                            <div class="col-md-4">'+data[i].sitename+'</div>\
                            <div class="col-md-4">'+data[i].sitelink+'</div>\
                            <div class="col-md-4">\
                                <button class="btn btn-danger" onClick="delete_competitor('+data[i].id+'    )">Delete</button>\
                            </div>\
                        </div>\
                    ');
                }

              });
        }
    }

    function delete_competitor(id){
        $.post("{% url 'products:delete_product_competitor' %}",
          {csrfmiddlewaretoken: '{{ csrf_token }}', id: id},
          function(data){
            $('#competitor' + id).remove();
          });
    }

    function fetch_product_details(id){
        $.post("{% url 'products:fetch_product_details' %}",
          {csrfmiddlewaretoken: '{{ csrf_token }}', id: {{product.id}}},
          function(data){
            $('.product_details_view_fetch_row').remove();
            for (var i=0; i<data.length; i++){
                $('.product_details_view_fetch').append('\
                    <div class="row product_details_view_fetch_row" style="font-weight: 700; ">\
                        <div class="col-md-4">'+data[i].url+'</div>\
                        <div class="col-md-4">'+data[i].original_price+'</div>\
                        <div class="col-md-4">'+data[i].promotion_price+'</div>\
                    </div>\
                ');
            }
          });
    }

    function detail_view(){
        $('.detail_view').toggle();
    }
    function competitors_view(){
        $('.competitors_view').toggle();
    }
    $( "#exampleModalBtn" ).click(function() {
        $('.error_div').empty();
    });

</script>
{% endblock %}